Making list of calibration images..
Traceback (most recent call last):
  File "/workspace/generate_images.py", line 61, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
./4_quant.sh: line 32: vai_q_tensorflow: command not found
./4_quant.sh: line 35: vai_q_tensorflow: command not found
